{
    "name": "Pharma PF Profile",
    "version": "17.0.1.0.0",
    "summary": "Verticalisation for Pharmacies in PF",
    "sequence": 30,
    "category": "Customization",
    "author": "INVITU SARL",
    "website": "https://github.com/invitu/odoo-pharmapf",
    "license": "AGPL-3",
    "images": [],
    "depends": [
        "base",
        "pharma_vertical",
    ],
    "data": [
        "data/res_partner.xml",
        "data/product_pricelist.xml",
        "data/res_config_settings.xml",
    ],
    "demo": [],
    "qweb": [],
    "installable": True,
    "application": False,
    "auto_install": False,
}
